server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    username: root
    password: realpongo
    url: jdbc:mariadb://localhost:3306/jackBlack
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect



